const categories = {
  expense: [
    { parent:'家庭生活', icon:'⌂', color:'#78a886', children:['水电燃气','房租房贷','日用家居','交通出行','医疗健康','外出用餐','其他生活'] },
    { parent:'买菜消费', icon:'🥬', color:'#e6a75e', children:['蔬菜水果','肉蛋水产','粮油调味','日常采购','外出用餐'] },
    { parent:'孩子学习', icon:'✎', color:'#8c88bd', children:['学费课程','书本文具','兴趣班','校内费用','学习用品'] },
    { parent:'休闲娱乐', icon:'☼', color:'#e98d7e', children:['家庭出游','影音娱乐','亲子活动','其他娱乐'] },
    { parent:'购物消费', icon:'◇', color:'#dc86a0', children:['衣物鞋包','数码家电','个人护理','其他购物'] },
    { parent:'人情往来', icon:'♡', color:'#d7a66e', children:['礼金红包','聚会请客','其他往来'] },
    { parent:'其他支出', icon:'⋯', color:'#9ba5a1', children:['其他'] }
  ],
  income: [
    { parent:'工资收入', icon:'▣', color:'#78a886', children:['工资','奖金','加班收入'] },
    { parent:'经营收入', icon:'↗', color:'#e6a75e', children:['经营所得','兼职收入'] },
    { parent:'理财收入', icon:'◒', color:'#8c88bd', children:['利息','投资收益'] },
    { parent:'其他收入', icon:'✧', color:'#e98d7e', children:['红包礼金','报销','其他'] }
  ]
};
const key='little-home-ledger-v1';
const now=new Date();
const fmtMoney=n=>'¥'+Number(n||0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
const fmtShort=n=>'¥'+Number(n||0).toLocaleString('zh-CN',{maximumFractionDigits:0});
const pad=n=>String(n).padStart(2,'0');
const dateKey=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const monthKey=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}`;
const escapeHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data=loadData();let goals=[];let currentRange='month';let statsDate=new Date(now.getFullYear(),now.getMonth(),1);let recordDate=new Date(now.getFullYear(),now.getMonth(),1);let recordRange='month';let recordFilter='all';let recordCategory=null;let entryType='expense';let selectedCategory=null;let selectedChild=null;let activeGoal=null;let activeGoalKind='free';let savingsUnlocked=false;let savingsCryptoKey=null;let pendingSetupSalt=null;
function loadData(){try{const v=JSON.parse(localStorage.getItem(key));if(Array.isArray(v))return v;}catch{}return seedData();}
function saveData(){localStorage.setItem(key,JSON.stringify(data));}
const goalKey='little-home-savings-goals-v1';
const encryptedGoalKey='little-home-savings-cipher-v1';
const passcodeMetaKey='little-home-savings-lock-v1';
function bytesToB64(bytes){return btoa(String.fromCharCode(...new Uint8Array(bytes)));}
function b64ToBytes(value){return Uint8Array.from(atob(value),c=>c.charCodeAt(0));}
async function deriveSavingsKey(passcode,salt){const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(passcode),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:310000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
async function saveGoals(){if(!savingsCryptoKey)throw new Error('savings_locked');const iv=crypto.getRandomValues(new Uint8Array(12));const cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},savingsCryptoKey,new TextEncoder().encode(JSON.stringify(goals)));localStorage.setItem(encryptedGoalKey,JSON.stringify({iv:bytesToB64(iv),data:bytesToB64(cipher)}));localStorage.removeItem(goalKey);}
async function decryptGoals(key){const value=localStorage.getItem(encryptedGoalKey);if(!value)return null;const packet=JSON.parse(value);const clear=await crypto.subtle.decrypt({name:'AES-GCM',iv:b64ToBytes(packet.iv)},key,b64ToBytes(packet.data));const parsed=JSON.parse(new TextDecoder().decode(clear));if(!Array.isArray(parsed))throw new Error('invalid_goals');return parsed;}
function hasSavingsPasscode(){return Boolean(localStorage.getItem(passcodeMetaKey));}
function seedGoals(){const later=(months)=>{const d=new Date(now.getFullYear(),now.getMonth()+months,1);return dateKey(d);};return [
 {id:crypto.randomUUID(),name:'家庭备用金',kind:'free',target:30000,saved:9600,deadline:later(10),demo:true},
 {id:crypto.randomUUID(),name:'孩子兴趣班',kind:'fixed',monthlyAmount:1200,target:12000,saved:4200,deadline:later(7),demo:true}
];}
function seedData(){const d=(day)=>`${dateKey(now).slice(0,7)}-${pad(day)}`;return [
 {id:crypto.randomUUID(),date:d(1),amount:128.6,type:'expense',parent:'买菜消费',child:'蔬菜水果',note:'一周的蔬菜水果'},
 {id:crypto.randomUUID(),date:d(2),amount:240,type:'expense',parent:'家庭生活',child:'水电燃气',note:'燃气费'},
 {id:crypto.randomUUID(),date:d(3),amount:86.5,type:'expense',parent:'买菜消费',child:'肉蛋水产',note:'菜市场采购'},
 {id:crypto.randomUUID(),date:d(4),amount:680,type:'expense',parent:'孩子学习',child:'兴趣班',note:'钢琴课'},
 {id:crypto.randomUUID(),date:d(5),amount:16800,type:'income',parent:'工资收入',child:'工资',note:'月薪到账'},
 {id:crypto.randomUUID(),date:d(5),amount:45,type:'expense',parent:'家庭生活',child:'交通出行',note:'地铁充值'},
 {id:crypto.randomUUID(),date:d(6),amount:156,type:'expense',parent:'买菜消费',child:'日常采购',note:'牛奶和日用品'},
 {id:crypto.randomUUID(),date:d(7),amount:320,type:'expense',parent:'孩子学习',child:'书本文具',note:'新学期文具'},
 {id:crypto.randomUUID(),date:d(8),amount:92,type:'expense',parent:'家庭生活',child:'外出用餐',note:'一家人早餐'}
];}
function totals(records){return records.reduce((a,r)=>{a[r.type]+=Number(r.amount);return a;},{income:0,expense:0});}
function inSelectedPeriod(r,date=statsDate,range=currentRange){return range==='month'?r.date.startsWith(monthKey(date)):r.date.startsWith(String(date.getFullYear()));}
function selectedRecords(){return data.filter(r=>!r.deletedAt&&inSelectedPeriod(r));}
function setPage(id){const current=document.querySelector('.page.active')?.id;if(current==='savingsPage'&&id!=='savingsPage'){savingsUnlocked=false;savingsCryptoKey=null;goals=[];}if(id==='savingsPage'&&!savingsUnlocked){showSavingsLock();return;}document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.page===id));window.scrollTo(0,0);if(id==='statsPage')renderStats();if(id==='recordsPage')renderRecords();if(id==='savingsPage')renderSavings();}
function showSavingsLock(){const existing=hasSavingsPasscode();document.getElementById('lockTitle').textContent=existing?'攒钱计划已加密':'为攒钱计划设置密码';document.getElementById('lockHint').textContent=existing?'请输入 6 位数字密码解锁。忘记密码只能清除计划并重新设置。':'设置一个 6 位数字密码。计划会在本机加密保存；忘记密码将无法恢复。';document.getElementById('lockConfirmField').classList.toggle('hidden',existing);document.getElementById('forgotSavings').classList.toggle('hidden',!existing);document.getElementById('unlockSavings').textContent=existing?'解锁并进入':'设置密码并进入';document.getElementById('lockPassword').value='';document.getElementById('lockPasswordConfirm').value='';document.getElementById('savingsLockBackdrop').classList.remove('hidden');}
async function enterSavings(){const pass=document.getElementById('lockPassword').value;if(!/^\d{6}$/.test(pass)){toast('请输入 6 位数字密码');return;}const metaRaw=localStorage.getItem(passcodeMetaKey);try{if(!metaRaw){if(document.getElementById('lockPasswordConfirm').value!==pass){toast('两次输入的密码不一致');return;}const salt=crypto.getRandomValues(new Uint8Array(16));savingsCryptoKey=await deriveSavingsKey(pass,salt);const legacy=JSON.parse(localStorage.getItem(goalKey)||'null');goals=Array.isArray(legacy)?legacy:seedGoals();localStorage.setItem(passcodeMetaKey,JSON.stringify({salt:bytesToB64(salt)}));await saveGoals();}else{const meta=JSON.parse(metaRaw);savingsCryptoKey=await deriveSavingsKey(pass,b64ToBytes(meta.salt));goals=await decryptGoals(savingsCryptoKey);if(!goals){const legacy=JSON.parse(localStorage.getItem(goalKey)||'null');goals=Array.isArray(legacy)?legacy:seedGoals();await saveGoals();}}savingsUnlocked=true;document.getElementById('savingsLockBackdrop').classList.add('hidden');setPage('savingsPage');}catch{goals=[];savingsCryptoKey=null;toast(metaRaw?'密码不正确':'密码设置失败，请重试');}}
function monthTitle(d){return `${d.getFullYear()}年${d.getMonth()+1}月`;}
function renderHome(){document.getElementById('todayLabel').textContent=`${now.getMonth()+1}月${now.getDate()}日 · ${['周日','周一','周二','周三','周四','周五','周六'][now.getDay()]}`;document.getElementById('homePeriod').textContent=monthTitle(now);const rows=data.filter(r=>!r.deletedAt&&r.date.startsWith(monthKey(now)));const t=totals(rows);document.getElementById('homeBalance').textContent=fmtMoney(t.income-t.expense);document.getElementById('homeIncome').textContent=fmtShort(t.income);document.getElementById('homeExpense').textContent=fmtShort(t.expense);document.getElementById('recordCount').textContent=`${rows.length} 笔`;const recent=[...rows].sort((a,b)=>b.date.localeCompare(a.date)||b.id.localeCompare(a.id)).slice(0,5);document.getElementById('recentList').innerHTML=recent.map(recordHTML).join('');document.getElementById('homeEmpty').classList.toggle('hidden',rows.length>0);document.getElementById('recentList').classList.toggle('hidden',!rows.length);renderFootprint();}
function renderFootprint(){const recorded=data.filter(r=>r.date),days=new Set(recorded.map(r=>r.date));document.getElementById('loggedDays').textContent=days.size;document.getElementById('loggedEntries').textContent=recorded.length;let cursor=new Date(now.getFullYear(),now.getMonth(),now.getDate());if(!days.has(dateKey(cursor)))cursor.setDate(cursor.getDate()-1);let streak=0;while(days.has(dateKey(cursor))&&streak<3660){streak++;cursor.setDate(cursor.getDate()-1);}document.getElementById('currentStreak').textContent=streak;const week=[];for(let i=6;i>=0;i--){const d=new Date(now.getFullYear(),now.getMonth(),now.getDate()-i);const key=dateKey(d);const count=recorded.filter(r=>r.date===key).length;week.push({day:['日','一','二','三','四','五','六'][d.getDay()],count,today:i===0});}const max=Math.max(1,...week.map(x=>x.count));document.getElementById('weekFootprint').innerHTML=week.map(x=>`<div class="week-day ${x.today?'today':''}"><span>${x.count||''}</span><i><b style="height:${x.count?Math.max(18,Math.round(x.count/max*100)):5}%"></b></i><small>${x.day}</small></div>`).join('');}
function renderSavings(){const targetTotal=goals.reduce((s,g)=>s+Number(g.target),0),savedTotal=goals.reduce((s,g)=>s+Number(g.saved),0),pct=targetTotal?Math.min(100,Math.round(savedTotal/targetTotal*100)):0;document.getElementById('savedTotal').textContent=fmtMoney(savedTotal);document.getElementById('overallPercent').textContent=`${pct}%`;document.getElementById('goalOverviewHint').textContent=goals.length?`共 ${goals.length} 个目标 · 还差 ${fmtMoney(Math.max(0,targetTotal-savedTotal))}`:'开始为心愿攒下一笔';document.getElementById('goalCount').textContent=`${goals.length} 个计划`;document.getElementById('overviewRing').style.background=`conic-gradient(#f7c873 ${pct}%, rgba(255,255,255,.2) ${pct}% 100%)`;document.getElementById('goalList').innerHTML=goals.map(goalHTML).join('');document.getElementById('goalsEmpty').classList.toggle('hidden',goals.length>0);document.getElementById('goalList').classList.toggle('hidden',!goals.length);}
function goalHTML(g){const target=Number(g.target)||0,saved=Number(g.saved)||0,pct=target?Math.min(100,Math.round(saved/target*100)):0;let pace=g.kind==='fixed'?`每月定额 ${fmtShort(g.monthlyAmount||0)}`:'不设期限，慢慢攒';if(g.kind!=='fixed'&&g.deadline){const days=Math.max(1,Math.ceil((new Date(g.deadline+'T12:00:00')-now)/86400000));const months=Math.max(1,Math.ceil(days/30));pace=saved>=target?'目标已达成':`建议每月攒 ${fmtShort(Math.ceil((target-saved)/months))}`;}const dateLabel=g.deadline?`${g.kind==='fixed'?'定额':'自由'}攒钱 · ${new Date(g.deadline+'T12:00:00').getMonth()+1}月${new Date(g.deadline+'T12:00:00').getDate()}日前`:`${g.kind==='fixed'?'定额':'自由'}攒钱 · 不限时间`;return `<article class="goal-card"><div class="goal-card-head"><div class="goal-emoji">${g.name.includes('孩子')?'✎':g.name.includes('旅行')||g.name.includes('旅游')?'✈':'✧'}</div><div class="goal-name"><strong>${escapeHtml(g.name)}</strong><span>${dateLabel}${g.demo?' · 示例':''}</span></div><button class="goal-delete" data-goal-delete="${g.id}" aria-label="删除${escapeHtml(g.name)}">···</button></div><div class="goal-progress-row"><div><span>已经攒下</span><strong>${fmtMoney(saved)}</strong></div><div class="goal-mini-ring" style="background:conic-gradient(#5d9b77 ${pct}%, #edf1ed ${pct}% 100%)"><span>${pct}%</span></div></div><div class="goal-progress-track"><i style="width:${pct}%"></i></div><div class="goal-foot"><span>目标 ${fmtShort(target)}</span><span>还差 ${fmtShort(Math.max(0,target-saved))}</span></div><div class="goal-plan-row"><span>✦ ${pace}</span><button data-goal-deposit="${g.id}">＋ 记一笔</button></div></article>`;}
function recordHTML(r){const cat=findCategory(r.type,r.parent);const icon=cat?.icon||'•';const created=r.createdAt?` · 录入 ${new Date(r.createdAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}`:'';const restored=r.restoredAt?` · 恢复于 ${new Date(r.restoredAt).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}`:'';if(r.deletedAt){const removed=new Date(r.deletedAt).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});return `<div class="record-row record-void"><div class="record-icon">${icon}</div><div class="record-main"><strong>${escapeHtml(r.child||r.parent)}</strong><span>${escapeHtml(r.parent)}${r.note?' · '+escapeHtml(r.note):''}${created} · 撤销于 ${removed}</span></div><div class="record-value muted">${r.type==='income'?'+':'−'}${fmtMoney(r.amount)}</div><button class="restore-record" data-restore="${r.id}" aria-label="恢复此记录">恢复</button></div>`;}return `<div class="record-row"><div class="record-icon">${icon}</div><div class="record-main"><strong>${escapeHtml(r.child||r.parent)}</strong><span>${escapeHtml(r.parent)}${r.note?' · '+escapeHtml(r.note):''}${created}${restored}</span></div><div class="record-value ${r.type}">${r.type==='income'?'+':'−'}${fmtMoney(r.amount)}</div><button class="delete-record" data-delete="${r.id}" aria-label="撤销此记录">×</button></div>`;}
function findCategory(type,parent){return categories[type].find(c=>c.parent===parent);}
function renderStats(){const records=selectedRecords(),t=totals(records);document.getElementById('statsPeriod').textContent=currentRange==='month'?monthTitle(statsDate):`${statsDate.getFullYear()}年`;document.getElementById('statsBalance').textContent=fmtMoney(t.income-t.expense);document.getElementById('statsIncome').textContent=fmtMoney(t.income);document.getElementById('statsExpense').textContent=fmtMoney(t.expense);document.getElementById('trendCaption').textContent=currentRange==='month'?'每天的收支变化':'每月的收支变化';renderTrend(records);renderCategories(records,t.expense);}
function renderTrend(records){const box=document.getElementById('trendChart');if(!records.length){box.innerHTML='<div class="empty-chart">这段时间还没有收支记录</div>';return;}const count=currentRange==='month'?new Date(statsDate.getFullYear(),statsDate.getMonth()+1,0).getDate():12;const buckets=Array.from({length:count},()=>({income:0,expense:0}));records.forEach(r=>{const d=new Date(r.date+'T12:00:00');const i=currentRange==='month'?d.getDate()-1:d.getMonth();if(buckets[i])buckets[i][r.type]+=Number(r.amount);});const max=Math.max(1,...buckets.flatMap(x=>[x.income,x.expense]));const w=340,h=122,left=8,right=8,top=9,bottom=20,chartH=h-top-bottom,chartW=w-left-right;const x=i=>left+(count===1?0:i*chartW/(count-1));const y=v=>top+chartH-(v/max)*chartH;const path=k=>buckets.map((b,i)=>`${i?'L':'M'}${x(i).toFixed(1)},${y(b[k]).toFixed(1)}`).join(' ');const area=k=>`${path(k)} L${x(count-1)},${top+chartH} L${x(0)},${top+chartH} Z`;let marks='';for(let j=0;j<3;j++){const yy=top+j*chartH/2;marks+=`<line class="chart-grid" x1="${left}" y1="${yy}" x2="${w-right}" y2="${yy}"/>`;}let labels='';(currentRange==='month'?[0,Math.floor((count-1)/2),count-1]:[0,3,6,9,11]).forEach(i=>{labels+=`<text class="chart-label" x="${x(i)}" y="${h-2}" text-anchor="middle">${currentRange==='month'?i+1+'日':i+1+'月'}</text>`;});let dots='';buckets.forEach((b,i)=>{if(b.income)dots+=`<circle class="chart-point-income" cx="${x(i)}" cy="${y(b.income)}" r="2.5"/>`;if(b.expense)dots+=`<circle class="chart-point-expense" cx="${x(i)}" cy="${y(b.expense)}" r="2.5"/>`;});box.innerHTML=`<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><defs><linearGradient id="fillIncome" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="#8ac5a0" stop-opacity=".2"/><stop offset="1" stop-color="#8ac5a0" stop-opacity="0"/></linearGradient><linearGradient id="fillExpense" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="#eea18f" stop-opacity=".16"/><stop offset="1" stop-color="#eea18f" stop-opacity="0"/></linearGradient></defs>${marks}<path class="chart-fill-income" d="${area('income')}"/><path class="chart-fill-expense" d="${area('expense')}"/><path class="chart-line-income" d="${path('income')}" fill="none" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/><path class="chart-line-expense" d="${path('expense')}" fill="none" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>${dots}${labels}</svg>`;}
function renderCategories(records,expenseTotal){const sums={};records.filter(r=>r.type==='expense').forEach(r=>sums[r.parent]=(sums[r.parent]||0)+Number(r.amount));const ordered=Object.entries(sums).sort((a,b)=>b[1]-a[1]);const colors=['#79ac89','#e4ad6b','#948fc0','#e78f7c','#d787a0','#d1a875','#aab2ad'];const donut=document.getElementById('categoryChart');if(!ordered.length){donut.innerHTML='<div class="empty-chart" style="width:100%">记录支出后，这里会显示分类占比</div>';document.getElementById('categoryList').innerHTML='<div class="empty-chart">暂无分类明细</div>';return;}let cursor=0;const stops=ordered.map(([name,val],i)=>{const from=cursor;cursor+=val/expenseTotal*100;return `${colors[i%colors.length]} ${from}% ${cursor}%`;}).join(',');donut.innerHTML=`<div class="donut" style="background:conic-gradient(${stops})"><div class="donut-center"><b>${fmtShort(expenseTotal)}</b><span>总支出</span></div></div><div class="legend-list">${ordered.slice(0,5).map(([name,val],i)=>`<div class="legend-item"><i style="background:${colors[i%colors.length]}"></i><span>${escapeHtml(name)}</span><b>${Math.round(val/expenseTotal*100)}%</b></div>`).join('')}</div>`;document.getElementById('categoryList').innerHTML=ordered.map(([name,val],i)=>{const cat=findCategory('expense',name);const count=records.filter(r=>r.type==='expense'&&r.parent===name).length;return `<button class="category-item" data-category="${escapeHtml(name)}"><span class="cat-icon" style="color:${colors[i%colors.length]}">${cat?.icon||'•'}</span><span class="category-copy"><strong>${escapeHtml(name)}</strong><span>${count} 笔 · 占支出 ${Math.round(val/expenseTotal*100)}%</span></span><span class="category-amount"><b>${fmtMoney(val)}</b><span>›</span></span></button>`;}).join('');}
function renderRecords(){const records=data.filter(r=>(recordRange==='year'?r.date.startsWith(String(recordDate.getFullYear())):r.date.startsWith(monthKey(recordDate)))&&(recordFilter==='deleted'?Boolean(r.deletedAt):!r.deletedAt&&(recordFilter==='all'||r.type===recordFilter))&&(!recordCategory||r.parent===recordCategory)).sort((a,b)=>b.date.localeCompare(a.date));document.getElementById('recordPeriod').textContent=(recordRange==='year'?`${recordDate.getFullYear()}年`:monthTitle(recordDate))+'⌄';document.querySelectorAll('.filter-chip').forEach(b=>b.classList.toggle('active',b.dataset.filter===recordFilter));const host=document.getElementById('allRecords');if(!records.length){host.innerHTML='';document.getElementById('recordsEmpty').querySelector('strong').textContent=recordFilter==='deleted'?'暂无撤销记录':'当前筛选下没有记录';document.getElementById('recordsEmpty').querySelector('span').textContent=recordFilter==='deleted'?'撤销的账目会保留在这里，之后也可以恢复':'可以换一个筛选条件，或记下新的一笔';document.getElementById('recordsEmpty').classList.remove('hidden');return;}document.getElementById('recordsEmpty').classList.add('hidden');const grouped={};records.forEach(r=>(grouped[r.date]??=[]).push(r));host.innerHTML=Object.entries(grouped).map(([date,items])=>{const t=totals(items);const d=new Date(date+'T12:00:00');return `<div class="date-group"><div class="date-heading"><span>${d.getMonth()+1}月${d.getDate()}日 · ${['周日','周一','周二','周三','周四','周五','周六'][d.getDay()]}</span><span>${recordFilter==='deleted'?`撤销 ${items.length} 笔`:`收 ${fmtShort(t.income)}　支 ${fmtShort(t.expense)}`}</span></div>${items.map(recordHTML).join('')}</div>`;}).join('');}
function openEntry(type='expense'){entryType=type;selectedCategory=null;selectedChild=null;document.querySelector('.entry-sheet').dataset.type=type;document.querySelectorAll('.type-switch button').forEach(b=>b.classList.toggle('selected',b.dataset.type===type));document.getElementById('amountInput').value='';document.getElementById('noteInput').value='';document.getElementById('dateInput').value=dateKey(now);renderCategoryPicker();document.getElementById('entryBackdrop').classList.remove('hidden');setTimeout(()=>document.getElementById('amountInput').focus(),120);}
function renderCategoryPicker(){document.getElementById('categoryPicker').innerHTML=categories[entryType].map(cat=>`<button class="category-option ${selectedCategory?.parent===cat.parent?'selected':''}" data-parent="${escapeHtml(cat.parent)}"><i>${cat.icon}</i><span>${escapeHtml(cat.parent)}</span></button>`).join('');const childBox=document.getElementById('childPicker');childBox.innerHTML=selectedCategory?`<div class="child-label">${escapeHtml(selectedCategory.parent)} · 选择细分</div><div class="child-options">${selectedCategory.children.map(c=>`<button class="child-option ${selectedChild===c?'selected':''}" data-child="${escapeHtml(c)}">${escapeHtml(c)}</button>`).join('')}</div>`:'';}
function closeEntry(){document.getElementById('entryBackdrop').classList.add('hidden');}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800);}
document.addEventListener('click',e=>{
  const tab=e.target.closest('.tab');if(tab){setPage(tab.dataset.page);return;}
  const go=e.target.closest('[data-go]');if(go){setPage(go.dataset.go+'Page');return;}
  const goalKind=e.target.closest('[data-goal-kind]');if(goalKind){activeGoalKind=goalKind.dataset.goalKind;document.querySelectorAll('.goal-type-switch button').forEach(b=>b.classList.toggle('selected',b===goalKind));document.getElementById('monthlyGoalField').classList.toggle('hidden',activeGoalKind!=='fixed');return;}
  const deposit=e.target.closest('[data-goal-deposit]');if(deposit){activeGoal=goals.find(g=>g.id===deposit.dataset.goalDeposit);if(activeGoal){document.getElementById('depositGoalName').textContent=`${activeGoal.name} · 已攒 ${fmtMoney(activeGoal.saved)}`;document.getElementById('depositAmount').value='';document.getElementById('depositBackdrop').classList.remove('hidden');}return;}
  const goalDelete=e.target.closest('[data-goal-delete]');if(goalDelete){const g=goals.find(x=>x.id===goalDelete.dataset.goalDelete);if(g&&confirm(`删除“${g.name}”这个攒钱计划？`)){goals=goals.filter(x=>x.id!==g.id);saveGoals().then(()=>{refresh();toast('计划已删除');});}return;}
  const type=e.target.closest('.type-switch button');if(type){entryType=type.dataset.type;selectedCategory=null;selectedChild=null;document.querySelector('.entry-sheet').dataset.type=entryType;document.querySelectorAll('.type-switch button').forEach(b=>b.classList.toggle('selected',b===type));renderCategoryPicker();return;}
  const cat=e.target.closest('.category-option');if(cat){const parent=cat.dataset.parent;if(selectedCategory?.parent!==parent){selectedCategory=findCategory(entryType,parent);selectedChild=null;}renderCategoryPicker();return;}
  const child=e.target.closest('.child-option');if(child){selectedChild=child.dataset.child;renderCategoryPicker();return;}
  const del=e.target.closest('[data-delete]');if(del){const record=data.find(r=>r.id===del.dataset.delete);if(record&&confirm('撤销这笔记录？记录会保留在“已撤销”历史中。')){record.deletedAt=new Date().toISOString();record.audit=[...(record.audit||[]),{action:'voided',at:record.deletedAt}];saveData();refresh();toast('已撤销，历史已保留');}return;}
  const restore=e.target.closest('[data-restore]');if(restore){const record=data.find(r=>r.id===restore.dataset.restore);if(record){record.restoredAt=new Date().toISOString();record.audit=[...(record.audit||[]),{action:'restored',at:record.restoredAt}];delete record.deletedAt;saveData();refresh();toast('记录已恢复');}return;}
  const ci=e.target.closest('[data-category]');if(ci){recordCategory=ci.dataset.category;recordFilter='expense';recordDate=new Date(statsDate);recordRange=currentRange;setPage('recordsPage');return;}
});
document.getElementById('quickAdd').onclick=()=>openEntry();document.getElementById('emptyAdd').onclick=()=>openEntry();document.getElementById('recordsAdd').onclick=()=>openEntry();document.getElementById('recordsEmptyAdd').onclick=()=>openEntry();document.getElementById('closeEntry').onclick=closeEntry;document.getElementById('entryBackdrop').addEventListener('click',e=>{if(e.target.id==='entryBackdrop')closeEntry();});
document.querySelectorAll('.filter-chip').forEach(b=>b.onclick=()=>{recordFilter=b.dataset.filter;recordCategory=null;renderRecords();});document.querySelectorAll('.segmented button').forEach(b=>b.onclick=()=>{currentRange=b.dataset.range;document.querySelectorAll('.segmented button').forEach(x=>x.classList.toggle('selected',x===b));renderStats();});document.getElementById('periodPrev').onclick=()=>{statsDate=currentRange==='month'?new Date(statsDate.getFullYear(),statsDate.getMonth()-1,1):new Date(statsDate.getFullYear()-1,0,1);renderStats();};document.getElementById('periodNext').onclick=()=>{statsDate=currentRange==='month'?new Date(statsDate.getFullYear(),statsDate.getMonth()+1,1):new Date(statsDate.getFullYear()+1,0,1);renderStats();};
document.getElementById('recordPeriod').onclick=()=>{const pick=prompt(recordRange==='year'?'请输入年份，例如：2026':'请输入月份，例如：2026-10',recordRange==='year'?String(recordDate.getFullYear()):monthKey(recordDate));if(recordRange==='year'&&pick&&/^\d{4}$/.test(pick)){recordDate=new Date(Number(pick),0,1);recordCategory=null;renderRecords();}else if(recordRange==='month'&&pick&&/^\d{4}-\d{2}$/.test(pick)){const [y,m]=pick.split('-').map(Number);if(m>=1&&m<=12){recordDate=new Date(y,m-1,1);recordCategory=null;renderRecords();}}};document.getElementById('homePeriod').onclick=()=>{setPage('statsPage');};
document.getElementById('saveEntry').onclick=()=>{const amount=Number(document.getElementById('amountInput').value);const date=document.getElementById('dateInput').value;if(!amount||amount<=0){toast('请输入有效金额');return;}if(!selectedCategory||!selectedChild){toast('请选择一级和二级分类');return;}const createdAt=new Date().toISOString();data.push({id:crypto.randomUUID(),createdAt,audit:[{action:'created',at:createdAt}],date,amount,type:entryType,parent:selectedCategory.parent,child:selectedChild,note:document.getElementById('noteInput').value.trim()});saveData();closeEntry();refresh();toast('记好了，辛苦啦');};
document.getElementById('newGoalBtn').onclick=()=>openGoal();document.getElementById('emptyGoalBtn').onclick=()=>openGoal();document.getElementById('closeGoal').onclick=()=>document.getElementById('goalBackdrop').classList.add('hidden');document.getElementById('closeDeposit').onclick=()=>document.getElementById('depositBackdrop').classList.add('hidden');document.getElementById('goalBackdrop').addEventListener('click',e=>{if(e.target.id==='goalBackdrop')e.currentTarget.classList.add('hidden');});document.getElementById('depositBackdrop').addEventListener('click',e=>{if(e.target.id==='depositBackdrop')e.currentTarget.classList.add('hidden');});
function openGoal(){activeGoalKind='free';document.querySelectorAll('.goal-type-switch button').forEach(b=>b.classList.toggle('selected',b.dataset.goalKind==='free'));document.getElementById('monthlyGoalField').classList.add('hidden');document.getElementById('goalName').value='';document.getElementById('goalTarget').value='';document.getElementById('goalMonthly').value='';document.getElementById('goalSaved').value='';document.getElementById('goalDate').value='';document.getElementById('goalBackdrop').classList.remove('hidden');}
document.getElementById('saveGoal').onclick=async()=>{const name=document.getElementById('goalName').value.trim(),target=Number(document.getElementById('goalTarget').value),saved=Number(document.getElementById('goalSaved').value||0),deadline=document.getElementById('goalDate').value,monthlyAmount=Number(document.getElementById('goalMonthly').value||0);if(!name){toast('先给计划起个名字');return;}if(!target||target<=0){toast('请输入有效的目标金额');return;}if(saved<0){toast('已攒金额不能小于零');return;}if(activeGoalKind==='fixed'&&monthlyAmount<=0){toast('请设置每月固定攒入金额');return;}goals.unshift({id:crypto.randomUUID(),name,kind:activeGoalKind,target,saved,deadline,monthlyAmount,demo:false});try{await saveGoals();document.getElementById('goalBackdrop').classList.add('hidden');refresh();toast('攒钱计划已创建');}catch{goals.shift();toast('保存失败，请确认攒钱页仍已解锁');}};
document.getElementById('saveDeposit').onclick=async()=>{const amount=Number(document.getElementById('depositAmount').value);if(!amount||amount<=0){toast('请输入攒入金额');return;}if(!activeGoal)return;activeGoal.saved=Number(activeGoal.saved)+amount;activeGoal.demo=false;try{await saveGoals();document.getElementById('depositBackdrop').classList.add('hidden');refresh();toast('已记入攒钱计划');}catch{activeGoal.saved-=amount;toast('保存失败，请重试');}};
document.getElementById('unlockSavings').onclick=enterSavings;document.getElementById('lockPassword').onkeydown=e=>{if(e.key==='Enter')enterSavings();};document.getElementById('lockPasswordConfirm').onkeydown=e=>{if(e.key==='Enter')enterSavings();};document.getElementById('cancelLock').onclick=()=>document.getElementById('savingsLockBackdrop').classList.add('hidden');document.getElementById('forgotSavings').onclick=()=>{if(confirm('这会永久删除本机加密保存的全部攒钱计划，之后可以重新设置密码。确定继续吗？')){localStorage.removeItem(encryptedGoalKey);localStorage.removeItem(passcodeMetaKey);localStorage.setItem(goalKey,'[]');goals=[];savingsCryptoKey=null;savingsUnlocked=false;setPage('homePage');showSavingsLock();}};document.getElementById('savingsLockBackdrop').addEventListener('click',e=>{if(e.target.id==='savingsLockBackdrop')e.currentTarget.classList.add('hidden');});document.addEventListener('visibilitychange',()=>{if(document.hidden&&document.getElementById('savingsPage').classList.contains('active'))setPage('homePage');});
document.getElementById('settingsBtn').onclick=()=>document.getElementById('settingsBackdrop').classList.remove('hidden');document.getElementById('closeSettings').onclick=()=>document.getElementById('settingsBackdrop').classList.add('hidden');document.getElementById('clearData').onclick=()=>{if(confirm('确定清空全部本地账目？此操作无法撤销。')){data=[];saveData();document.getElementById('settingsBackdrop').classList.add('hidden');refresh();toast('本地账目已清空');}};
function refresh(){renderHome();renderStats();renderSavings();if(document.getElementById('recordsPage').classList.contains('active'))renderRecords();}
renderHome();renderStats();renderRecords();renderSavings();
